speech-to-text/recognize-stream.js
The library should support the use of a customization_id when present and not use the model parameter.  The customization_id corresponds to a trained language model that should be used over a specified model name.
=> ENH: Added the ability to specify a customization_id.  

README.md, text-to-speech/synthesize.js
Added optional parameter 'customization_id' to Text-To-Speech syntheize() function
Solves Issue Issue #38: Optional parameter 'customization_id' for Text-To-Speech synthesize is missing.
=> FIX Issue #38: added optional parameter 'customization_id' to Text-To-Speech syntheize() function

.gitignore, README.md, examples/static/microphone-streaming-auto-stop.html, speech-to-text/recognize-stream.js
Remove continuous flag that is no longer supported
- [x ] `npm test` passes (tip: `npm run autofix` can correct most style issues)
- [x ] readme and/or JSDoc is updated
=> remove continuous from OPENING_MESSAGE_PARAMS_ALLOWED

examples/static/browserify-app.js, examples/static/microphone-streaming-auto-stop.html, examples/static/webpack-app.js, speech-to-text/recognize-file.js, speech-to-text/recognize-microphone.js
The `continuous` parameter was removed from the speech-to-text API last month. I found remnants of this parameter being specified in a few places. 
This PR removes these references.
=> removed continuous parameter from all remaining speech-to-text code/examples

dist/watson-speech.js, speech-to-text/content-type.js, speech-to-text/file-player.js, speech-to-text/recognize-stream.js
Added webm to headerContentTypes as was previously missing in content-types.js
=> Added webm to headerContentTypes 

README.md, speech-to-text/get-models.js, speech-to-text/recognize-file.js, speech-to-text/recognize-microphone.js, speech-to-text/recognize-stream.js, text-to-speech/get-voices.js, text-to-speech/synthesize.js, util/querystring.js
I implemented this a bit differently than I did in the Node SDK, because in this code we don’t have a built-in way of knowing if the service is using IAM or not. 
So, what I did was leave the `watson-token` code untouched and simply added a new option, `access_token`, that the user will have to intentionally provide if they ware using IAM. I updated the code to handle this and updated the documentation. Let me know what you think about this change. I can also update my PR in the Node SDK to match what I did here if you would prefer.
Currently, tests are failing. Not sure why but I will update this PR accordingly when I find out.
UPDATE: Tests are now passing. Have not added any new tests.
=> provide an option for access_token

speech-to-text/recognize-stream.js
Changing the JSDoc comments in RecognizeStream to match the service behavior. These are the same changes as made in the Node SDK.
The tests fail because of a linting error addressed in PR #71
=> remove incorrect default descriptions in jsdoc comments - DONT MERGE

speech-to-text/recognize-stream.js
Reverts watson-developer-cloud/speech-javascript-sdk#72
=> Revert "remove incorrect default descriptions in jsdoc comments - DONT MERGE"

speech-to-text/recognize-stream.js
Changing the JSDoc comments in RecognizeStream to match the service behavior. These are the same changes as made in the Node SDK.
Tests pass, ready for merge.
=> remove incorrect default descriptions in jsdoc comments

speech-to-text/recognize-microphone.js, speech-to-text/recognize-stream.js
Hello,
This PR will introduce the ability to pass an acoustic_customization_id.
https://www.ibm.com/watson/developercloud/speech-to-text/api/v1/curl.html?curl#websocket_methods
**CI**
I'm not sure why the CI is failing.
=> add support for acoustic_customization_id

speech-to-text/recognize-stream.js
The service default for `interim_results` is `false`, not `true`. Updating the JSDocs.
=> docs: fix jsdocs to use correct default for interim_results

dist/watson-speech.js, examples/static/speaker-labels-file-console.html, examples/static/speaker-stream-file-console.html, examples/static/speaker-stream-file-html.html, speech-to-text/format-stream.js
Updates `.shtml` links that would cause redirects if users tried to use them. These links were updated with the correct URL.
Resolves #79
=> docs: updates .shtml links to new urls

README.md, speech-to-text/get-models.js, text-to-speech/get-voices.js, text-to-speech/synthesize.js
Added an option for user to provide their own URL everywhere it seemed appropriate:
- text-to-speech/synthesize
- text-to-speech/getVoices
- speech-to-text/getModels
Updated the JSDocs and README.
=> feat: add option for user-provided URL in `synthesize`

dist/watson-speech.js
In SDK v.0.36 with Firefox 60.3.0esr (64-bit), using the new IAM API Key authentication for Text to Speech, the synthesize method filters out the access_token parameter.
```
var params = {
text: "Hello",
voice: "en-US_MichaelVoice",
access_token: "<ACCESS_TOKEN>"
};
stream = WatsonSpeech.TextToSpeech.synthesize(params);
```
The requested URI resource doesn't include this access token and the watson-token parameter is undefined, returning a CORS error.
```
https://stream.watsonplatform.net/text-to-speech/api/v1/synthesize?voice=en-US_MichaelVoice&text=Hello&watson-token=**undefined**
```
---
There should also be a check that token parameter is defined, given it's either token or access_token. 
```
module.exports = function synthesize(options) {
if (!options || (!options.token && …
```
=> Synthesize method does not honor access_token from IAM API Key

text-to-speech/synthesize.js
Don't force use of `watson-token` now that `access_token` is an allowed query parameter for authenticating with IAM.
Resolves #96
=> fix: dont force use of `watson-token` as a query param

examples/package-lock.json, examples/package.json, package-lock.json, package.json
This PR bumps the dependency `watson-developer-cloud` to `3.18.1`, the latest version.
We mainly need the features released in `3.13.1` which contain bug fixes to `lib/recognize-stream`, the only module of the Node SDK we use here. These fixes allow `language_customization_id` to be used as a parameter for recognize.
=> upgrade watson-developer-cloud to 3.18.1

examples/package-lock.json, examples/package.json
It looked like there was a version 0.36.0 for this package, but there was just a release tag, nothing on NPM. Changing this back to always pull in the latest version.
=> chore: revert change to specific version of watson-speech

package-lock.json, package.json
Moves `watson-developer-cloud` from `devDependencies` to `dependencies`.
Also updates `watson-developer-cloud` to fix a bug that prevents this package from working with services using IAM.
=> Move node sdk dependency

examples/server.js, speech-to-text/index.js, speech-to-text/recognize-file.js, speech-to-text/recognize-microphone.js, speech-to-text/recognize-stream.js, text-to-speech/synthesize.js, util/querystring.js
This PR should fix the bugs users are reporting:
- `language_customization_id` not working
- `access_token` not working
I fixed these bugs in the `watson-developer-cloud` dependency, but other updates to that package introduced a regression here and broke the build. So, I reverted the change where we made `RecognizeStream` a dependency and added it back to the code. This is a _temporary_ solution while we make changes to the Node SDK and figure out how to support them here.
=> Stabilize package

.babelrc
Resolves #120 
The babel config only supports one kind of export by default. The `sourceType` parameter needs to be set to `unambiguous` in order to use both. More documentation [here](https://babeljs.io/docs/en/options#sourcetype).
=> fix: allow exports when using babel

.travis.yml
The tests for this package use the pre-built code. This means it is possible for the tests to pass but the build to fail due to `webpack` errors, etc that aren't necessary due to the code operating incorrectly.
To ensure only build-ready code makes it into the repo, we should run the build step on Travis.
=> build: run webpack on travis to catch any build failures during ci

examples/server.js
The Authorization SDK will only use the URL passed into the constructor if a callback is presented as the first argument. An argument could be made that this should change in that SDK but since we are using a constructor-passed URL in the examples, I'm just removing the empty object argument which fixes the problem.
Resolves #124
=> Fix live examples

text-to-speech/synthesize.js
While using Text-to-speech feature,  google chrome autoplay didn't work. 
This is the exact issue experienced.
https://developers.google.com/web/updates/2017/06/play-request-was-interrupted
=> fix: Chrome autoplay

speech-to-text/recognize-stream.js
For using a grammar in speech recognition requests to restrict the set of phrases that the service can recognize from audio, I would like to enable to add `grammar_name` to a WebSocket message.
https://cloud.ibm.com/docs/services/speech-to-text?topic=speech-to-text-grammarUse
=> feat: allow to add grammar_name parameter to opening message

speech-to-text/recognize-stream.js
The recognize parameters are out of date with the service. Updating these parameters to exactly match the node sdk.
Resolves #137
=> fix: accept all supported parameters in recognize-stream

package-lock.json, package.json
The package `watson-developer-cloud` is not actually used anywhere in the code, just in the tests/examples. Therefore, there is no reason for it to be included in the production dependencies. This PR moves the package to `devDependencies` so that it will no longer be included in the production release.
Marking this as a performance change, so it will trigger a patch release.
=> perf: move wdc dependency to devDependencies for smaller package size

CHANGELOG.md, examples/server.js, examples/static/index.html, examples/static/microphone-alternatives.html, examples/static/microphone-streaming-text-to-console.html, examples/static/microphone-word-confidence.html, examples/static/speaker-labels-file-console.html, examples/static/speaker-stream-file-html.html, package-lock.json, package.json, speech-to-text/get-models.js, speech-to-text/recognize-file.js, speech-to-text/recognize-microphone.js, speech-to-text/recognize-stream.js, test/resources/offline_test_server.js, text-to-speech/get-voices.js, text-to-speech/synthesize.js, util/process-user-parameters.js
* this is to match the recent changes in the watson node sdk
* `access_token` is renamed to `accessToken` in all modules
This certainly presents breaking changes but I don't know that the library is ready for 1.0 so I suppose we're taking advantage of the fact that we're in pre-release.
=> feat: update parameter names in recognize/synthesize streams to be lower camel case

docs/TEXT-TO-SPEECH.md, examples/.env.example, speech-to-text/get-models.js, speech-to-text/recognize-file.js, speech-to-text/recognize-microphone.js, speech-to-text/recognize-stream.js, text-to-speech/get-voices.js, text-to-speech/synthesize.js
=> fix(urls): update deprecated watsonplatform.net urls

CHANGELOG.md, package-lock.json, package.json, speech-to-text/recognize-stream.js
Updated some vulnerable dependencies, added support for `character_insertion_bias` websocket param for STT:
https://cloud.ibm.com/docs/speech-to-text?topic=speech-to-text-parsing#insertion-bias
```sh
> watson-speech@0.40.1 test-offline
> karma start --single-run
08 09 2022 12:10:13.062:INFO [http.server]: Starting
08 09 2022 12:10:13.125:INFO [http.server]: setting up token & api servers for offline test
08 09 2022 12:10:13.126:INFO [http.server]: Done
08 09 2022 12:10:15.125:INFO [framework.browserify]: bundle built
08 09 2022 12:10:15.140:INFO [karma-server]: Karma v6.3.16 server started at http://localhost:9876/
08 09 2022 12:10:15.140:INFO [launcher]: Launching browsers FirefoxAutoGUM with concurrency unlimited
08 09 2022 12:10:15.143:INFO [launcher]: Starting browser Firefox
08 09 …
```
=> Update dependencies, support character_insertion_bias websocket param

text-to-speech/synthesize.js
=> add pitch_percentage to allow list of parameters
